name: Deploy drdblaze to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET 8
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    
    # Install wasm-tools
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools
    
    # Install Azure Artifacts Credential Provider
    - name: Install Azure Artifacts Credential Provider
      run: |
        mkdir -p ~/.nuget/plugins/netcore/
        curl -L https://aka.ms/install-artifacts-credprovider.sh | bash

    # Restore dependencies
    - name: Restore NuGet packages
      
      env:
        # Enable credential provider session token cache
        NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: "true"   
        VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"https://drdmohssine.pkgs.visualstudio.com/MSLibraries/_packaging/MSPkgFeed/nuget/v3/index.json", "password":"${{ secrets.AZURE_ARTIFACTS_PAT }}"}]'
        
      run: dotnet restore
       
        
    # publishes Blazor project to the release-folder
    - name: Publish .NET 8 Project
      run: dotnet publish drdblaze.csproj -c Release -o release --nologo
      
      
    # changes the base-tag in index.html from '/' to 'drdblaze' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to drdblaze
      run: sed -i 's/<base href="\/" \/>/<base href="\/drdblaze\/" \/>/g' release/wwwroot/index.html

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
    
        
